
language: c++

dist: trusty
sudo: required

env:
  global:
    - MAKEFLAGS="-j 2"
    - CCACHE_CPP2=1

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y zip unzip p7zip xz-utils make binutils gcc g++ clang tcc pkg-config help2man doxygen autoconf autoconf-archive automake libtool ccache zlib1g-dev libmpg123-dev libogg-dev libvorbis-dev portaudio19-dev libpulse-dev libflac-dev libsndfile1-dev libltdl-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip xz help2man doxygen autoconf-archive mpg123 libogg libvorbis portaudio flac libsndfile ; fi

install:
  - true

script:
  - ./build/auto/dist.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild clean -workspace build/xcode-macosx/libopenmpt.xcworkspace/ -scheme libopenmpt ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild build -workspace build/xcode-macosx/libopenmpt.xcworkspace/ -scheme libopenmpt -configuration Release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild clean -workspace build/xcode-iphoneos/libopenmpt.xcworkspace/ -scheme libopenmpt ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild build -workspace build/xcode-iphoneos/libopenmpt.xcworkspace/ -scheme libopenmpt -configuration Release -sdk iphoneos IPHONEOS_DEPLOYMENT_TARGET='10.0' ARCHS='armv7 armv7s arm64' CONFIGURATION_BUILD_DIR=../../bin/test/arm ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild build -workspace build/xcode-iphoneos/libopenmpt.xcworkspace/ -scheme libopenmpt -configuration Release -sdk iphonesimulator IPHONEOS_DEPLOYMENT_TARGET='10.0' ARCHS='i386 x86_64' CONFIGURATION_BUILD_DIR=../../bin/test/x86 ; fi

