

branches:
  only:
    - master

skip_tags: true

skip_branch_with_pr: true



image: Visual Studio 2017

clone_depth: 2500

cache:
  - build\externals

install:
  - build\download_externals.cmd auto



build_script:
  - build\auto\build_openmpt_args.cmd vs2017 default Win32 Release
  - build\auto\build_openmpt_args.cmd vs2017 default x64   Release

after_build:
  - build\auto\package_openmpt_args.cmd vs2017 default Win32 Release
  - build\auto\package_openmpt_args.cmd vs2017 default x64   Release
  - appveyor PushArtifact bin\openmpt-win32.tar
  - appveyor PushArtifact bin\openmpt-win64.tar



test: off

